title: UCSC Events Calendar Docs
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  UCSC's Events Calendar Documentation
url: "https://ucsc.github.io/events-calendar/"
remote_theme: pages-themes/cayman@v0.2.0
google_analytics: false
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-gfm-admonitions

# Build settings
markdown: kramdown
kramdown:
  auto_ids: false
  parse_block_html: false

admin:
  admin_name: "Jason Chafin"
  admin_title: "Senior Web Developer, C&amp;M Web Team"
  admin_dpt: "Communications &amp; Marketing"
  admin_div: "University Relations"
  admin_url: "https://campusdirectory.ucsc.edu/cd_detail?uid=jchafin"
  admin_email: "jchafin@ucsc.edu"
